debug: false

# For plugins to identify which server it is in.
# Also used for various communications between servers in the network
server_name: ""

# PvE world already let arrow go thru, it's useless now :clown:
arrow-shoots-thru-players-worlds:
  - example

# Configs for developer chat
dev-chat:
  prefix: "<aqua>[<red>Dev<aqua>]"
  color: "<aqua>"

# Configs for Redis server that defaults to localhost:6379
# Usage: Developer chat
# Requires server restart to reconnect because we only use localhost anyway and idh time to implement it yet :)
redis:
  host: localhost
  port: 6379
  username: ''
  password: ''

# Configs for MYySQL server that defaults to localhost:3306
# Usage: Accessory Rework
mysql:
  host: localhost
  port: 3306
  username: ''
  password: ''
  database: database_name
  hikari-cp:
    MaximumPoolSize: 5
    MinimumIdle: 2
    IdleTimeout: 300000

# To fix immortal mobs by checking if mob's health is still > 0 after death, force remove it if true.
# Limitation of this option is that cancelevent ~onDeath in MythicMobs will not be usable anymore.
fix-immortal-mob: false

# DO NOT TOUCH BEFORE ACCESSORY REWORK UPDATE
# Requires a server restart
enable-claimaccessories-command: false

# The FileRotater automatically changes files
# What else is there to say
auto-rotate-files: false

# Configs for AutoCheat detection
AutoCaptcha:
  CommandExecuted: captchaopen %playername%
  # 1 in X Chance to trigger. Set to -1
  Fishing: 500
  MobKills: -1