name: HoloUtils
version: ${project.version}
main: me.lehreeeee.HoloUtils.HoloUtils
authors: [Lehreeeee, Benloti]
api-version: '1.21'

# To steal their /a command :)
loadbefore: [mcMMO]
# Optional
softdepend: [PlaceholderAPI, ModelEngine, MMOItems, MythicMobs]

commands:
  holoutils:
    description: Main command for HoloUtils
    aliases: [hu]
    permission: holoutils.admin
  playertitle:
    description: Command for playertitle
    aliases: [ ptitle ]
    permission: holoutils.playertitle
  devchat:
    description: Command for devchat
    aliases: [a]
    permission: holoutils.devchat
  claimaccessories:
    description: Command for claiming accessories
    permission: holoutils.claimaccessories
  reroll:
    description: Command for rerolling mmoitem's random stats
    permission: holoutils.reroll
  eventrewards:
    description: Command for claiming rewards obtained from events