name: HoloUtils
version: '1.0.0'
main: me.lehreeeee.HoloUtils.HoloUtils
api-version: '1.21'

commands:
  holoutils:
    description: Main command for HoloUtils
    aliases: [hu, hutils]
    permission: holoutils.admin