name: HoloUtils
version: ${project.version}
main: me.lehreeeee.HoloUtils.HoloUtils
author: Lehreeeee
api-version: '1.21'

# To steal their /a command :)
loadbefore: [mcMMO]
# Optional
softdepend: [PlaceholderAPI, ModelEngine]

commands:
  holoutils:
    description: Main command for HoloUtils
    aliases: [hu, hutils]
  devchat:
    description: Command for devchat
    aliases: [a]
    permission: holoutils.devchat