name: HoloUtils
version: ${project.version}
main: me.lehreeeee.HoloUtils.HoloUtils
api-version: '1.21'

commands:
  holoutils:
    description: Main command for HoloUtils
    aliases: [hu, hutils]
    permission: holoutils.admin