name: HoloUtils
version: ${project.version}
main: me.lehreeeee.HoloUtils.HoloUtils
author: Lehreeeee
api-version: '1.21'

loadbefore: [mcMMO]

commands:
  holoutils:
    description: Main command for HoloUtils
    aliases: [hu, hutils]
    permission: holoutils.admin
  devchat:
    description: Command for devchat
    aliases: [a, dchat]
    permission: holoutils.devchat